openeducat_erp/__openerp__.py
openeducat_erp/doc/changelog.rst
openeducat_erp/wizard/generate_time_table.py

Change little issues & Add Release point.

Add Tag & Release 8.0.1.1.0

---

openeducat_erp/i18n/sl.po

A simple translation correction.

State as subregion, not state as state of mind!

---

openeducat_erp/i18n/vi_VN.po

Please accept this Vietnamese translation

Add Vietnamese Translation

---

README.md
openeducat_activity/__manifest__.py
openeducat_admission/__manifest__.py
openeducat_admission/test/admission_register_creation.yml
openeducat_assignment/__manifest__.py
openeducat_attendance/__manifest__.py
openeducat_classroom/__manifest__.py
openeducat_core/__manifest__.py
openeducat_erp/__manifest__.py
openeducat_erp/doc/changelog.rst
openeducat_exam/__manifest__.py
openeducat_facility/__manifest__.py
openeducat_fees/__manifest__.py
openeducat_library/__manifest__.py
openeducat_parent/__manifest__.py
openeducat_support/__manifest__.py
openeducat_timetable/__manifest__.py
web_openeducat/__manifest__.py

- Added renew media feature for library.
- Enhanced the penalty calculation.
- Added sequence for library card & media unit barcode.
- Added barcode interface for library media unit issue. `Enterprise`
- Added dashboard for librarian. `Enterprise`
- Enhanced admission process & added fees term feature.
- Added multiple course admission for single student.
- Added elective subject & student can opt.
- Added fees reminder for students. 'Enterprise`
- Added feature of online admission process. 'Enterprise`
- Enhanced hostel management with broad coverage of campus. `Enterprise`
- Added invoicing feature for campus facilities. `Enterprise`
- Enhanced the transportation with trips & students per stop. `Enterprise`
- Added classroom detail in session(timetable) generation and manage states.
- …

[REL] v10.0.3.0.0

---

openeducat_activity/i18n/pt_BR.po
openeducat_admission/i18n/pt_BR.po
openeducat_assignment/i18n/pt_BR.po
openeducat_attendance/i18n/pt_BR.po
openeducat_classroom/i18n/pt_BR.po
openeducat_core/i18n/pt_BR.po
openeducat_exam/i18n/pt_BR.po
openeducat_facility/i18n/pt_BR.po
openeducat_fees/i18n/pt_BR.po
openeducat_library/i18n/pt_BR.po
openeducat_parent/i18n/pt_BR.po
openeducat_timetable/i18n/pt_BR.po

Added Portuguese Brazil translation file for openeducat_core module - Odoo 10.0

Portuguese Brazil translation for openeducat_core module 10.0

---

openeducat_admission/admission_menu.xml
openeducat_admission/views/admission_register_view.xml
openeducat_admission/views/admission_view.xml
openeducat_assignment/views/assignment_sub_line_view.xml
openeducat_attendance/attendance_menu.xml
openeducat_attendance/models/attendance_line.py
openeducat_attendance/views/attendance_line_view.xml
openeducat_core/views/faculty_view.xml
openeducat_core/views/student_view.xml
openeducat_timetable/timetable_menu.xml
openeducat_timetable/views/timetable_view.xml

[add]:#1101:openeducat:pivot reports

---

openeducat_attendance/security/op_attendance_security.xml

Faculties will now be able to create Attendance lines..

[FIX] Allow Faculty to create Attendance Lines

---

openeducat_activity/i18n/zh.po
openeducat_admission/i18n/zh.po
openeducat_assignment/i18n/zh.po
openeducat_attendance/i18n/zh.po
openeducat_classroom/i18n/zh.po
openeducat_core/i18n/zh.po
openeducat_exam/i18n/zh.po
openeducat_facility/i18n/zh.po
openeducat_fees/i18n/zh.po
openeducat_library/i18n/zh.po
openeducat_parent/i18n/zh.po
openeducat_timetable/i18n/zh.po

Added Chinese Translations ...

[ADD] Chinese Translations

---

openeducat_core/menu/openeducat_core_menu.xml
openeducat_fees/fees_menu.xml

Changes in core and fees menus

[FIX] remove report menus from fees

---

openeducat_assignment/models/assignment.py
openeducat_assignment/models/assignment_sub_line.py
openeducat_assignment/views/assignment_sub_line_view.xml

Did changes in onchange of course to get related subjects based on the selected course in assignment.
To student the marks field in assignment submission will only be displayed when assignment is accepted.

[IMP]:Changes in onchange of course and marks attrs

---

openeducat_library/models/library.py
openeducat_library/report/report_menu.xml
openeducat_library/report/report_student_library_card.xml

Link library card with student profile When library card create for the student

[FIX] Library : Link Library Card With Student Profile

---

openeducat_core/views/faculty_view.xml
openeducat_core/views/student_view.xml

[FIX] avatar.png path

---

openeducat_timetable/models/timetable.py

Avoid duplicated entries in mail.followers to fails sql_constraint

[FIX] Timetable: Avoid duplicated entries in mail.followers

---

openeducat_library/models/account_invoice.py
openeducat_library/models/media_movement.py
openeducat_library/security/library_security.xml
openeducat_library/views/media_movement_view.xml

Solved : 
Record Rules
Return Done Issue after invoice payment
On change issued date  and return date
Fields visibility/readonly state

 [FIX] Library : Issues in Media Movement and Security 

---

openeducat_parent/security/ir.model.access.csv
openeducat_parent/security/op_security.xml

add record rule for back office to access parent details

[FIX] Parent: Record rules for admin and parent

---

openeducat_timetable/report/report_timetable_student_generate.xml
openeducat_timetable/report/report_timetable_teacher_generate.xml
openeducat_timetable/report/timetable_report_student.py
openeducat_timetable/report/timetable_report_teacher.py

Issue in report py during convert date format

[FIX] Timetable: Report issue for convert date

---

openeducat_core/models/student.py
openeducat_library/views/media_view.xml

Update core module for set unique sql constrain on student for GR Number
Set fa icons for accept, reject and for request again buttons for media request on all media view

[IMP] Student: Unique GR number, Library: Set fa icons for media request lines in all media

---

openeducat_core/menu/faculty_menu.xml
openeducat_core/models/batch.py
openeducat_core/models/course.py
openeducat_core/models/faculty.py
openeducat_core/models/student.py
openeducat_core/models/subject.py
openeducat_core/report/report_menu.xml
openeducat_core/views/batch_view.xml
openeducat_core/views/course_view.xml
openeducat_core/views/faculty_view.xml
openeducat_core/views/student_view.xml
openeducat_core/views/subject_view.xml
openeducat_core/wizard/faculty_create_employee_wizard.py
openeducat_fees/report/fees_analysis_report.py
openeducat_fees/report/fees_analysis_report_view.xml

Logger in 
- Batch
- Course
- Faculty
- Student
- Subject

[IMP] Update core modules

---

openeducat_exam/__manifest__.py
openeducat_exam/demo/exam_demo.xml
openeducat_exam/demo/exam_session_demo.xml
openeducat_exam/demo/marksheet_line_demo.xml
openeducat_exam/demo/marksheet_register_demo.xml
openeducat_exam/demo/result_line_demo.xml
openeducat_exam/models/exam.py
openeducat_exam/models/exam_session.py
openeducat_exam/models/marksheet_line.py
openeducat_exam/models/marksheet_register.py
openeducat_exam/models/result_template.py
openeducat_exam/report/report_ticket.xml
openeducat_exam/security/op_security.xml
openeducat_exam/views/exam_session_view.xml
openeducat_exam/wizard/student_hall_tickets_wizard.py

1 - Update demodata.
- exam session
- exam
- marksheet register
- marksheet line
- result tempalte
- result line
2 - Remove singleton error.
3 - Introduce state in session.
4 - Update field with domain for session references.

[IMP] Update exam module

---

openeducat_admission/models/admission.py
openeducat_admission/models/admission_register.py
openeducat_fees/models/fees_terms.py
openeducat_fees/models/student.py
openeducat_fees/report/fees_analysis_report.py
openeducat_fees/views/fees_terms_view.xml

Logger in fees term and update labels

[IMP] Update fees module

---

openeducat_core/models/res_config_setting.py
openeducat_core/views/res_config_setting_view.xml

I have added Secure QR Configuration in res.config file for OpenEduCat Secure Module.

[15.0][ADD] Added Secure QR Configuration
